using MediatR;
using EnterpriseMdmSolution.Core.Common;
using EnterpriseMdmSolution.Application.Modules.MaterialQualityInspection.DTOs;

namespace EnterpriseMdmSolution.Application.Modules.MaterialQualityInspection.Queries;

public sealed record SearchMaterialQualityInspectionsQuery(SearchMaterialQualityInspectionDto Search) : IRequest<PagedResult<MaterialQualityInspectionDto>>;