using MediatR;
using EnterpriseMdmSolution.Application.Modules.CustomerClassification.DTOs;

namespace EnterpriseMdmSolution.Application.Modules.CustomerClassification.Commands;

public sealed record CreateCustomerClassificationCommand(CreateCustomerClassificationDto Input) : IRequest<CustomerClassificationDto>;